line-length = 88
target-version = "py39"

lint.select = [
    "E4", "E7", "E9", "F", "I", "B", "C4", "UP"
]

lint.ignore = []

force-exclude = true
exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "build",
    "dist",
]

[lint.isort]
lines-after-imports = 2
known-first-party = ["telegram_ai_agent"]
lines-between-types = 1

case-sensitive = true
force-wrap-aliases = true
combine-as-imports = true
default-section = "third-party"

[format]
docstring-code-format = true
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
